name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:

  sdk: ">=2.12.0 <4.0.0"
  # sdk: ^3.9.0
  # sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^14.0.2
  http: ^1.5.0
  flutter_spinkit: ^5.2.2
  # cupertino_icons: ^1.0.8
  # cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900